# The .lagoon.yml file is the central file to set up your project. It contains configuration in order to do the following:
#
#  Define routes for accessing your sites.
#  Define pre-rollout tasks.
#  Define post-rollout tasks.
#  Set up SSL certificates.
#  Add cron jobs for environments.

docker-compose-yaml: docker-compose.yml

project: concretecms-base

tasks:
  pre-rollout:
    - run:
        name: entities refresh on cli pod
        command: |
          if [[ $(/app/vendor/bin/concrete c5:is-installed) == "Concrete is installed" ]]; then
            /app/vendor/bin/concrete c5:entities:refresh
          fi
        service: cli
        shell: bash
    - run:
        name: entities refresh on nginx pod
        command: |
          if [[ $(/app/vendor/bin/concrete c5:is-installed) == "Concrete is installed" ]]; then
            /app/vendor/bin/concrete c5:entities:refresh
          fi
        service: nginx
        container: php
        shell: bash