# The .lagoon.yml file is the central file to set up your project. It contains configuration in order to do the following:
#
#  Define routes for accessing your sites.
#  Define pre-rollout tasks.
#  Define post-rollout tasks.
#  Set up SSL certificates.
#  Add cron jobs for environments.

docker-compose-yaml: docker-compose.yml

project: concretecms-base

tasks:
  pre-rollout:
    - run:
        name: Backup DB before updating Concrete CMS
        command: |
          mkdir -p /app/db-backup && \
          mysqldump --no-tablespaces -h $MARIADB_HOST -u $MARIADB_USERNAME -p$MARIADB_PASSWORD $MARIADB_DATABASE > /app/db-backup/db-backup-$(date +%Y%m%d%H%M%S).sql
        service: cli
  post-rollout:
    - run:
        name: update language files
        command: /app/vendor/bin/concrete c5:install-language --add ja_JP
        service: nginx
        container: php
    - run:
        name: Run Concrete CMS c5:update
        command: /app/vendor/bin/concrete c5:update --env=live
        service: cli

environments:
  main:
    cronjobs:
      - name: messenger consume
        schedule: "M * * * *" # Once per hour, at a random minute.
        command: /app/vendor/bin/concrete messenger:consume async --time-limit=3600
        service: cli
      - name: scheduling worker
        schedule: "* * * * *" # Every minute.
        command: /app/vendor/bin/concrete concrete:scheduler:run
        service: cli

lagoon-sync:
  mariadb:
    type: mariadb
    config:
      hostname: "${MARIADB_HOST:-mariadb}"
      username: "${MARIADB_USERNAME:-lagoon}"
      password: "${MARIADB_PASSWORD:-lagoon}"
      port:     "${MARIADB_PORT:-3306}"
      database: "${MARIADB_DATABASE:-lagoon}"
    local:
      config:
        hostname: "${MARIADB_HOST:-mariadb}"
        username: "${MARIADB_USERNAME:-lagoon}"
        password: "${MARIADB_PASSWORD:-lagoon}"
        port:     "${MARIADB_PORT:-3306}"
        database: "${MARIADB_DATABASE:-lagoon}"
  cli:
    type: files
    config:
      sync-directory: "/app/web/application/files/"
  cli-config:
    type: files
    config:
      sync-directory: "/app/web/application/config/generated_overrides/"