# The .lagoon.yml file is the central file to set up your project. It contains configuration in order to do the following:
#
#  Define routes for accessing your sites.
#  Define pre-rollout tasks.
#  Define post-rollout tasks.
#  Set up SSL certificates.
#  Add cron jobs for environments.

docker-compose-yaml: docker-compose.yml

project: concretecms-base

tasks:
  pre-rollout:
    - run:
        name: update language files
        command: |
          if [[ "$(/app/vendor/bin/concrete c5:is-installed)" == "Concrete is installed" ]]; then
            /app/vendor/bin/concrete c5:language-install --add ja_JP;
          fi
        service: nginx
        container: php

environments:
  master:
    cronjobs:
      - name: messenger consume
        schedule: "M * * * *" # Once per hour, at a random minute.
        command: /app/scripts/check_and_run.sh /app/vendor/bin/concrete messenger:consume async --time-limit=3600
        service: cli
      - name: scheduling worker
        schedule: "* * * * *" # Every minute.
        command: /app/scripts/check_and_run.sh /app/vendor/bin/concrete concrete:scheduler:run
        service: cli