x-lagoon-project:
  &lagoon-project concretecms-base

x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - .:/app:delegated ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
      - files:/app/web/application/files
      - config:/app/web/application/config/generated_overrides

x-environment:
  &default-environment
    LAGOON_PROJECT: *lagoon-project
    # Route that should be used locally
    LAGOON_ROUTE: &default-url http://${COMPOSE_PROJECT_NAME:-concretecms-base}.docker.amazee.io
    # Uncomment if you like to have the system behave like in production
    #LAGOON_ENVIRONMENT_TYPE: production
    # Uncomment to enable xdebug and then restart via `docker compose up -d`
    #XDEBUG_ENABLE: "true"

volumes:
  files:
  db:
  config:
    labels:
      lagoon.type: persistent

services:

  cli: # cli container, will be used for executing composer and any local commands.
    build:
      context: .
      dockerfile: lagoon/cli.dockerfile
    image: &cli-image ${COMPOSE_PROJECT_NAME:-concretecms-base}-cli # this image will be reused as `CLI_IMAGE` in subsequent Docker builds
    labels:
      # Lagoon labels
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx # mount the persistent storage of nginx into this container
      lagoon.persistent: /app/web/application/files/ # location where the persistent storage should be mounted
      lagoon.volumes.config.path: /app/web/application/config/generated_overrides/ # location where the additional storage should be mounted
      lando.type: php-cli
    << : *default-volumes # loads the defined volumes from the top
    volumes_from: ### mount the ssh-agent from the pygmy or cachalot ssh-agent. Automatically removed in CI.
      - container:amazeeio-ssh-agent ### Local overrides to mount host SSH keys. Automatically removed in CI.
    environment:
      << : *default-environment # loads the defined environment variables from the top

  nginx:
    build:
      context: .
      dockerfile: lagoon/nginx.dockerfile
      args:
        CLI_IMAGE: *cli-image # Inject the name of the cli image
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/web/application/files/ # location where the persistent storage should be mounted
      lagoon.volumes.config.path: /app/web/application/config/generated_overrides/ # location where the additional storage should be mounted
      lando.type: nginx
    ports:
      - "8080" # exposes the port 8080 with a random local port, find it with `docker-compose port nginx 8080`
    << : *default-volumes
    depends_on:
      - cli # basically just tells docker-compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top
      LAGOON_LOCALDEV_URL: *default-url
    networks:
      - amazeeio-network
      - default

  php:
    build:
      context: .
      dockerfile: lagoon/php.dockerfile
      args:
        CLI_IMAGE: *cli-image
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
      lagoon.persistent: /app/web/application/files/
      lagoon.volumes.config.path: /app/web/application/config/generated_overrides/
      lando.type: php-fpm
    << : *default-volumes
    depends_on:
      - cli # basically just tells docker compose to build the cli first
    environment:
      << : *default-environment # loads the defined environment variables from the top

  mariadb:
    image: uselagoon/mariadb-10.11:latest
    labels:
      lagoon.type: mariadb
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    environment:
      << : *default-environment
      TZ: "Asia/Tokyo" # Set the timezone same as the php.ini
    volumes:
      - db:/var/lib/mysql

networks:
  amazeeio-network:
    external: true